<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>13</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.BinarySerialization.Sliced" Version="15.0.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CK.EmbeddedResources" Version="4.0.0" />
    <PackageReference Include="CK.Engine.TypeCollector" Version="35.0.0" />
  </ItemGroup>
</Project>